obj-m := omen_rgb_keyboard.o

# Include directories
ccflags-y := -I$(src)/include

# Module components organized by directory
omen_rgb_keyboard-y := \
	wmi/omen_wmi.o \
	fan/omen_fan.o \
	zones/omen_zones.o \
	animations/omen_animations.o \
	state/omen_state.o \
	hda/omen_hda_led.o \
	core/omen_rgb_keyboard_main.o
