[package]
name = "omenrgb-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "omenrgb-gui"
path = "src/main.rs"

[dependencies]
omenrgb-core = { path = "../omenrgb-core" }
eframe = "0.31"
egui = "0.31"
image = { version = "0.25", default-features = false, features = ["png", "gif"] }
gif = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ksni = { version = "0.3", default-features = false, features = ["async-io"] }
async-io = "2"
